// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHQxZPs91EafMQI4yqUvqnQjkclL68bBg',
    appId: '1:160192558110:web:d58eee3b422e3b9f1f2a0f',
    messagingSenderId: '160192558110',
    projectId: 'ingilizce-ogrenme-6f609',
    authDomain: 'ingilizce-ogrenme-6f609.firebaseapp.com',
    storageBucket: 'ingilizce-ogrenme-6f609.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpMucjDyF_sM_etFWeti8GQ9MmhSsf5aU',
    appId: '1:160192558110:android:395f9adc29a970af1f2a0f',
    messagingSenderId: '160192558110',
    projectId: 'ingilizce-ogrenme-6f609',
    storageBucket: 'ingilizce-ogrenme-6f609.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB22i1CAMkRdBZX_Cs59O6AA92k7VmK1rQ',
    appId: '1:160192558110:ios:d3365f7f9c0617a51f2a0f',
    messagingSenderId: '160192558110',
    projectId: 'ingilizce-ogrenme-6f609',
    storageBucket: 'ingilizce-ogrenme-6f609.firebasestorage.app',
    iosBundleId: 'com.example.finalprojesi1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB22i1CAMkRdBZX_Cs59O6AA92k7VmK1rQ',
    appId: '1:160192558110:ios:d3365f7f9c0617a51f2a0f',
    messagingSenderId: '160192558110',
    projectId: 'ingilizce-ogrenme-6f609',
    storageBucket: 'ingilizce-ogrenme-6f609.firebasestorage.app',
    iosBundleId: 'com.example.finalprojesi1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHQxZPs91EafMQI4yqUvqnQjkclL68bBg',
    appId: '1:160192558110:web:dbe4dce0e851030b1f2a0f',
    messagingSenderId: '160192558110',
    projectId: 'ingilizce-ogrenme-6f609',
    authDomain: 'ingilizce-ogrenme-6f609.firebaseapp.com',
    storageBucket: 'ingilizce-ogrenme-6f609.firebasestorage.app',
  );
}
